# Generated by Django 3.1 on 2020-09-01 12:29

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=5, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_jp', models.CharField(blank=True, max_length=100, null=True)),
                ('name_rj', models.CharField(blank=True, max_length=100, null=True)),
                ('url_homepage', models.URLField(blank=True, max_length=255, null=True)),
                ('url_blog', models.URLField(blank=True, max_length=255, null=True)),
                ('url_twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('url_pixiv', models.URLField(blank=True, max_length=255, null=True)),
                ('profile_img', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profiles/')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.CharField(blank=True, max_length=25, null=True)),
                ('version', models.IntegerField(blank=True, default=0, null=True)),
                ('name_en', models.CharField(blank=True, max_length=150, null=True)),
                ('name_jp', models.CharField(blank=True, max_length=150, null=True)),
                ('name_rj', models.CharField(blank=True, max_length=150, null=True)),
                ('released', models.DateField(blank=True, null=True)),
                ('num_pages_orig', models.IntegerField(blank=True, null=True)),
                ('num_pages_user', models.IntegerField(blank=True, null=True)),
                ('lang_orig', models.IntegerField(blank=True, choices=[(1, 'Unknown'), (2, 'English'), (3, 'Japanese'), (4, 'Chinese'), (5, 'Korean'), (6, 'French'), (7, 'German'), (8, 'Spanish'), (9, 'Italian'), (10, 'Russian')], default=1, null=True)),
                ('lang_user', models.IntegerField(blank=True, choices=[(1, 'Unknown'), (2, 'English'), (3, 'Japanese'), (4, 'Chinese'), (5, 'Korean'), (6, 'French'), (7, 'German'), (8, 'Spanish'), (9, 'Italian'), (10, 'Russian')], default=1, null=True)),
                ('user_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('is_adult', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=1)),
                ('is_anthology', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('is_decensored', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('is_colored', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('is_digital', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('is_favorite', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('is_viewed', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('is_hidden', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('foldername', models.TextField(unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=5, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_jp', models.CharField(blank=True, max_length=100, null=True)),
                ('name_rj', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=5, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_jp', models.CharField(blank=True, max_length=100, null=True)),
                ('name_rj', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=5, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_jp', models.CharField(blank=True, max_length=100, null=True)),
                ('name_rj', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.IntegerField()),
                ('width_orig', models.IntegerField(blank=True, null=True)),
                ('height_orig', models.IntegerField(blank=True, null=True)),
                ('orientation_orig', models.CharField(blank=True, max_length=10, null=True)),
                ('is_cover', models.BooleanField(default=False)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('filename', models.TextField()),
                ('page_thumb_lg', imagekit.models.fields.ProcessedImageField(blank=True, default='placeholders/book_default_thumb.jpg', null=True, upload_to='pages/')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=5, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_jp', models.CharField(blank=True, max_length=100, null=True)),
                ('name_rj', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=5, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_jp', models.CharField(blank=True, max_length=100, null=True)),
                ('name_rj', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=5, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_jp', models.CharField(blank=True, max_length=100, null=True)),
                ('name_rj', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='type',
            constraint=models.UniqueConstraint(fields=('web_id',), name='type_unq'),
        ),
        migrations.AddConstraint(
            model_name='publisher',
            constraint=models.UniqueConstraint(fields=('web_id',), name='publisher_unq'),
        ),
        migrations.AddConstraint(
            model_name='parody',
            constraint=models.UniqueConstraint(fields=('web_id',), name='parody_unq'),
        ),
        migrations.AddField(
            model_name='page',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='dou.book'),
        ),
        migrations.AddConstraint(
            model_name='convention',
            constraint=models.UniqueConstraint(fields=('web_id',), name='convention_unq'),
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.UniqueConstraint(fields=('web_id',), name='content_unq'),
        ),
        migrations.AddConstraint(
            model_name='circle',
            constraint=models.UniqueConstraint(fields=('web_id',), name='circle_unq'),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='dou.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='circles',
            field=models.ManyToManyField(blank=True, to='dou.Circle'),
        ),
        migrations.AddField(
            model_name='book',
            name='contents',
            field=models.ManyToManyField(blank=True, to='dou.Content'),
        ),
        migrations.AddField(
            model_name='book',
            name='conventions',
            field=models.ManyToManyField(blank=True, to='dou.Convention'),
        ),
        migrations.AddField(
            model_name='book',
            name='parodies',
            field=models.ManyToManyField(blank=True, to='dou.Parody'),
        ),
        migrations.AddField(
            model_name='book',
            name='publishers',
            field=models.ManyToManyField(blank=True, to='dou.Publisher'),
        ),
        migrations.AddField(
            model_name='book',
            name='types',
            field=models.ManyToManyField(blank=True, to='dou.Type'),
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('web_id',), name='author_unq'),
        ),
    ]
