# Generated by Django 2.2.2 on 2019-06-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dou', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='convention',
        ),
        migrations.RemoveField(
            model_name='convention',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='convention',
            name='start_date',
        ),
        migrations.AddField(
            model_name='book',
            name='conventions',
            field=models.ManyToManyField(blank=True, to='dou.Convention'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='type',
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.ManyToManyField(blank=True, to='dou.Type'),
        ),
    ]
