# Generated by Django 2.2.2 on 2019-06-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dou', '0002_auto_20190626_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='type',
            new_name='types',
        ),
    ]
