# Generated by Django 2.2.2 on 2019-06-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dou', '0003_auto_20190627_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=5, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_jp', models.CharField(blank=True, max_length=100, null=True)),
                ('name_rj', models.CharField(blank=True, max_length=100, null=True)),
                ('url_personal', models.URLField(blank=True, max_length=255, null=True)),
                ('url_twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('url_pixiv', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('web_id',), name='author_unq'),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='dou.Author'),
        ),
    ]
