# Generated by Django 2.2.2 on 2019-06-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dou', '0004_auto_20190627_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='url_personal',
            new_name='url_blog',
        ),
        migrations.AddField(
            model_name='author',
            name='url_homepage',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
