# Generated by Django 2.2.2 on 2019-06-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dou', '0005_auto_20190628_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='img_profile',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
