# Generated by Django 2.2.2 on 2019-06-30 08:19

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dou', '0006_author_img_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
