# Generated by Django 2.2.2 on 2019-07-01 11:55

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dou', '0007_book_cover_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='img_profile',
        ),
        migrations.AddField(
            model_name='author',
            name='profile_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
