# Generated by Django 2.2.2 on 2019-07-17 08:23

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dou', '0008_auto_20190701_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='url',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='covers/book_default_thumb.jpg', null=True, upload_to='covers/'),
        ),
    ]
