# Generated by Django 2.2.2 on 2019-07-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dou', '0009_auto_20190717_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='colored',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='decensored',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='digital',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='translation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
