# Generated by Django 2.2.2 on 2019-07-19 10:50

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dou', '0010_auto_20190717_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='placeholders/book_default_thumb.jpg', null=True, upload_to='covers/'),
        ),
    ]
