# Generated by Django 2.2.2 on 2019-07-19 12:40

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dou', '0011_auto_20190719_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_img',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_thumb_lg',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='placeholders/book_default_thumb.jpg', null=True, upload_to='covers/thumb_lg/'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_thumb_sm',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='placeholders/book_default_thumb.jpg', null=True, upload_to='covers/thumb_sm/'),
        ),
        migrations.AddField(
            model_name='book',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
