# Generated by Django 2.2.2 on 2019-08-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dou', '0012_auto_20190719_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_palette',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
