# Generated by Django 2.2.2 on 2019-08-07 11:45

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dou', '0013_book_cover_palette'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(blank=True, max_length=25, null=True)),
                ('page_number', models.CharField(blank=True, max_length=5, null=True)),
                ('page_thumb_lg', imagekit.models.fields.ProcessedImageField(blank=True, default='placeholders/book_default_thumb.jpg', null=True, upload_to='')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='dou.Book')),
            ],
        ),
    ]
